// Seed content for the P0 loop. Only Mathematics has real cards for now —
// every other subject is listed (so Home/Progress show the full CBC subject
// set) but starts empty until a content-source decision is made.
//
// Bump SEED_VERSION whenever this file's cards change. On next launch,
// db.ts wipes and re-inserts the `cards` table when the device's stored
// seed_version is behind — so content edits actually reach devices that
// already seeded an earlier version, without wiping grade/streak/stars.

export const SEED_VERSION = 8;

export type Subject = {
  id: string;
  name: string;
  emoji: string;
};

export const SUBJECTS: Subject[] = [
  { id: 'math', name: 'Mathematics', emoji: '🔢' },
  { id: 'english', name: 'English', emoji: '🔤' },
  { id: 'kiswahili', name: 'Kiswahili', emoji: '🗣️' },
  { id: 'science', name: 'Integrated Science', emoji: '🔬' },
  { id: 'social', name: 'Social Studies', emoji: '🌍' },
  { id: 'creative', name: 'Creative Arts', emoji: '🎨' },
  { id: 're', name: 'Religious Education', emoji: '📖' },
];

export type SeedCard = {
  id: string;
  subjectId: string;
  grade: number;
  topic: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
};

// Grade 4 Mathematics, covering the KICD strands: Numbers, Measurement,
// Geometry (Data Handling and Algebra are left for later — see memory).
export const SEED_CARDS: SeedCard[] = [
  // --- Numbers: Whole Numbers ---
  {
    id: 'math-4-wholenumbers-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Whole Numbers',
    question: 'What is the value of 5 in the number 5,432?',
    options: ['5,000', '500', '50', '5'],
    correctIndex: 0,
    explanation: '5 is in the thousands place, so it stands for 5,000.',
  },
  {
    id: 'math-4-wholenumbers-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Whole Numbers',
    question: 'What is 3,456 + 2,145?',
    options: ['5,601', '5,501', '6,601', '5,611'],
    correctIndex: 0,
    explanation: 'Add ones, tens, hundreds, then thousands: 3,456 + 2,145 = 5,601.',
  },
  {
    id: 'math-4-wholenumbers-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Whole Numbers',
    question: 'What is 4,820 − 1,365?',
    options: ['3,455', '3,545', '3,365', '2,455'],
    correctIndex: 0,
    explanation: 'Subtracting column by column from the ones: 4,820 − 1,365 = 3,455.',
  },
  {
    id: 'math-4-wholenumbers-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Whole Numbers',
    question: 'What is 24 × 6?',
    options: ['144', '148', '134', '124'],
    correctIndex: 0,
    explanation: '24 × 6 = (20 × 6) + (4 × 6) = 120 + 24 = 144.',
  },
  {
    id: 'math-4-wholenumbers-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Whole Numbers',
    question: 'Share 72 mangoes equally among 8 children. How many does each child get?',
    options: ['9', '8', '7', '12'],
    correctIndex: 0,
    explanation: '72 ÷ 8 = 9 mangoes each.',
  },
  {
    id: 'math-4-wholenumbers-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Whole Numbers',
    question: 'Which number is the largest?',
    options: ['8,452', '8,425', '8,254', '8,245'],
    correctIndex: 0,
    explanation: 'Compare from the left: all start with 8,4__ except two — then compare the hundreds digit; 8,452 has the biggest hundreds digit among them.',
  },

  // --- Numbers: Fractions ---
  {
    id: 'math-4-fractions-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'Which fraction is the same as 2/4?',
    options: ['1/2', '1/4', '3/4', '2/2'],
    correctIndex: 0,
    explanation: '2/4 and 1/2 are equivalent fractions — both mean half.',
  },
  {
    id: 'math-4-fractions-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'Which fraction is bigger, 1/3 or 1/4?',
    options: ['1/3', '1/4', 'They are equal', 'Cannot tell'],
    correctIndex: 0,
    explanation:
      'When the top numbers are equal, the fraction with the smaller bottom number is bigger — a whole split into fewer pieces means each piece is larger.',
  },
  {
    id: 'math-4-fractions-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'A pizza is cut into 8 equal slices. Amani eats 3 slices. What fraction did Amani eat?',
    options: ['3/8', '8/3', '3/5', '5/8'],
    correctIndex: 0,
    explanation: '3 slices out of 8 equal slices is written as 3/8.',
  },
  {
    id: 'math-4-fractions-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'What is 1/2 + 1/4?',
    options: ['3/4', '2/6', '1/6', '2/4'],
    correctIndex: 0,
    explanation: '1/2 is the same as 2/4, so 2/4 + 1/4 = 3/4.',
  },
  {
    id: 'math-4-fractions-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'Which of these fractions equals a whole number?',
    options: ['4/4', '3/4', '1/4', '2/4'],
    correctIndex: 0,
    explanation: '4/4 means all 4 equal parts are used — that is one whole.',
  },
  {
    id: 'math-4-fractions-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'Which fraction is smallest?',
    options: ['1/8', '1/2', '1/4', '1/3'],
    correctIndex: 0,
    explanation:
      'The more pieces a whole is split into, the smaller each piece is — eighths are smaller than halves, thirds, or quarters.',
  },
  {
    id: 'math-4-fractions-7',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'Which of these is an improper fraction (top number bigger than the bottom)?',
    options: ['5/4', '3/4', '1/4', '2/5'],
    correctIndex: 0,
    explanation: 'In 5/4 the top number (5) is bigger than the bottom number (4) — that means more than one whole.',
  },
  {
    id: 'math-4-fractions-8',
    subjectId: 'math',
    grade: 4,
    topic: 'Fractions',
    question: 'There are 12 apples. 1/4 of them are red. How many apples are red?',
    options: ['3', '4', '6', '12'],
    correctIndex: 0,
    explanation: 'Finding 1/4 of 12 means sharing 12 into 4 equal groups: 12 ÷ 4 = 3.',
  },

  // --- Measurement: Length & Mass ---
  {
    id: 'math-4-lengthmass-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Length & Mass',
    question: 'How many centimetres are in 1 metre?',
    options: ['100', '10', '1,000', '60'],
    correctIndex: 0,
    explanation: '1 metre = 100 centimetres.',
  },
  {
    id: 'math-4-lengthmass-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Length & Mass',
    question: 'A pencil is 15 cm long. About how many pencils placed end to end make 1 metre?',
    options: ['Between 6 and 7', 'Between 3 and 4', 'Between 10 and 11', 'Between 1 and 2'],
    correctIndex: 0,
    explanation: '100 cm ÷ 15 cm ≈ 6.7, so about 6 or 7 pencils.',
  },
  {
    id: 'math-4-lengthmass-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Length & Mass',
    question: 'How many grams are in 1 kilogram?',
    options: ['1,000', '100', '10', '500'],
    correctIndex: 0,
    explanation: '1 kilogram = 1,000 grams.',
  },
  {
    id: 'math-4-lengthmass-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Length & Mass',
    question: 'A bag of maize flour weighs 2 kg. How many grams is that?',
    options: ['2,000 g', '200 g', '20 g', '20,000 g'],
    correctIndex: 0,
    explanation: '2 kg × 1,000 g = 2,000 g.',
  },
  {
    id: 'math-4-lengthmass-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Length & Mass',
    question: 'Which is heavier: 1 kg of sugar, or 900 g of sugar?',
    options: ['1 kg', '900 g', 'They are equal', 'Cannot tell'],
    correctIndex: 0,
    explanation: '1 kg = 1,000 g, which is more than 900 g.',
  },
  {
    id: 'math-4-lengthmass-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Length & Mass',
    question: "Amani's height is 128 cm. What is that in metres and centimetres?",
    options: ['1 m 28 cm', '12 m 8 cm', '1 m 8 cm', '2 m 8 cm'],
    correctIndex: 0,
    explanation: '128 cm = 100 cm + 28 cm = 1 m 28 cm.',
  },

  // --- Measurement: Capacity & Time ---
  {
    id: 'math-4-capacitytime-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Capacity & Time',
    question: 'How many millilitres are in 1 litre?',
    options: ['1,000', '100', '10', '500'],
    correctIndex: 0,
    explanation: '1 litre = 1,000 millilitres.',
  },
  {
    id: 'math-4-capacitytime-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Capacity & Time',
    question: 'A jug holds 2 litres of water. How many millilitres is that?',
    options: ['2,000 ml', '200 ml', '20 ml', '20,000 ml'],
    correctIndex: 0,
    explanation: '2 litres × 1,000 ml = 2,000 ml.',
  },
  {
    id: 'math-4-capacitytime-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Capacity & Time',
    question: 'How many minutes are in 1 hour?',
    options: ['60', '100', '30', '24'],
    correctIndex: 0,
    explanation: '1 hour = 60 minutes.',
  },
  {
    id: 'math-4-capacitytime-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Capacity & Time',
    question: 'School starts at 8:00 am and a lesson lasts 45 minutes. What time does the lesson end?',
    options: ['8:45 am', '9:00 am', '8:30 am', '9:15 am'],
    correctIndex: 0,
    explanation: '8:00 am + 45 minutes = 8:45 am.',
  },
  {
    id: 'math-4-capacitytime-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Capacity & Time',
    question: 'How many hours are in a full day?',
    options: ['24', '12', '60', '7'],
    correctIndex: 0,
    explanation: 'A full day has 24 hours.',
  },
  {
    id: 'math-4-capacitytime-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Capacity & Time',
    question: 'A tank has 5 litres of water. 2,000 ml is poured out. How many litres are left?',
    options: ['3 litres', '2 litres', '4 litres', '1 litre'],
    correctIndex: 0,
    explanation: '2,000 ml = 2 litres, so 5 − 2 = 3 litres.',
  },

  // --- Measurement: Money ---
  {
    id: 'math-4-money-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Money',
    question: 'Amani has a KSh 200 note and buys a book for KSh 150. How much change should she get?',
    options: ['KSh 50', 'KSh 350', 'KSh 100', 'KSh 40'],
    correctIndex: 0,
    explanation: '200 − 150 = 50.',
  },
  {
    id: 'math-4-money-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Money',
    question: 'You have a KSh 20 coin and a KSh 10 coin. How much money do you have in total?',
    options: ['KSh 30', 'KSh 20', 'KSh 10', 'KSh 200'],
    correctIndex: 0,
    explanation: '20 + 10 = 30.',
  },
  {
    id: 'math-4-money-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Money',
    question: 'A pencil costs KSh 15 and a rubber costs KSh 10. How much do both cost together?',
    options: ['KSh 25', 'KSh 15', 'KSh 20', 'KSh 5'],
    correctIndex: 0,
    explanation: '15 + 10 = 25.',
  },
  {
    id: 'math-4-money-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Money',
    question: 'Baraka saves KSh 50 every week. How much will he save in 4 weeks?',
    options: ['KSh 200', 'KSh 150', 'KSh 100', 'KSh 54'],
    correctIndex: 0,
    explanation: '50 × 4 = 200.',
  },
  {
    id: 'math-4-money-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Money',
    question: 'Which is more money: 5 coins of KSh 20, or 1 note of KSh 100?',
    options: ['They are equal', '5 coins of KSh 20', '1 note of KSh 100', 'Cannot tell'],
    correctIndex: 0,
    explanation: '5 × 20 = 100, so they are equal.',
  },
  {
    id: 'math-4-money-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Money',
    question: 'A shopkeeper had KSh 500 and sold goods worth KSh 180. How much money does she have now?',
    options: ['KSh 320', 'KSh 380', 'KSh 420', 'KSh 280'],
    correctIndex: 0,
    explanation: '500 − 180 = 320.',
  },

  // --- Geometry: Shapes & Angles ---
  {
    id: 'math-4-shapesangles-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Shapes & Angles',
    question: 'How many sides does a triangle have?',
    options: ['3', '4', '5', '6'],
    correctIndex: 0,
    explanation: 'A triangle always has 3 sides.',
  },
  {
    id: 'math-4-shapesangles-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Shapes & Angles',
    question: 'A shape with 4 equal sides and 4 right angles is called a ___.',
    options: ['Square', 'Rectangle', 'Triangle', 'Circle'],
    correctIndex: 0,
    explanation: 'A square has 4 equal sides and 4 right angles.',
  },
  {
    id: 'math-4-shapesangles-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Shapes & Angles',
    question: 'How many right angles does a rectangle have?',
    options: ['4', '2', '3', '1'],
    correctIndex: 0,
    explanation: 'Every corner of a rectangle is a right angle — that is 4 in total.',
  },
  {
    id: 'math-4-shapesangles-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Shapes & Angles',
    question: 'An angle smaller than a right angle is called a(n) ___.',
    options: ['Acute angle', 'Obtuse angle', 'Straight angle', 'Reflex angle'],
    correctIndex: 0,
    explanation: 'An acute angle is any angle smaller than a right angle (90°).',
  },
  {
    id: 'math-4-shapesangles-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Shapes & Angles',
    question: 'If you are facing North and turn to face East, which way did you turn?',
    options: ['Right (clockwise)', 'Left (anticlockwise)', 'You turned all the way around', 'You did not turn'],
    correctIndex: 0,
    explanation: 'Facing North then turning to East is a quarter-turn to the right (clockwise).',
  },
  {
    id: 'math-4-shapesangles-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Shapes & Angles',
    question: 'How many sides does a pentagon have?',
    options: ['5', '4', '6', '3'],
    correctIndex: 0,
    explanation: 'A pentagon has 5 sides.',
  },

  // --- Algebra: Patterns ---
  {
    id: 'math-4-patterns-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Patterns',
    question: 'What is the next number in this pattern? 2, 4, 6, 8, ___',
    options: ['10', '9', '12', '11'],
    correctIndex: 0,
    explanation: 'This pattern adds 2 each time: 8 + 2 = 10.',
  },
  {
    id: 'math-4-patterns-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Patterns',
    question: 'What is the missing number? 5, 10, 15, ___, 25',
    options: ['20', '18', '22', '19'],
    correctIndex: 0,
    explanation: 'This pattern adds 5 each time: 15 + 5 = 20.',
  },
  {
    id: 'math-4-patterns-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Patterns',
    question: 'Which of these is a pattern of odd numbers?',
    options: ['1, 3, 5, 7', '2, 4, 6, 8', '1, 2, 3, 4', '5, 10, 15, 20'],
    correctIndex: 0,
    explanation: 'Odd numbers cannot be split into two equal groups — 1, 3, 5, 7 are all odd.',
  },
  {
    id: 'math-4-patterns-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Patterns',
    question: 'What is the next number? 3, 6, 9, 12, ___',
    options: ['15', '14', '16', '13'],
    correctIndex: 0,
    explanation: 'This pattern adds 3 each time: 12 + 3 = 15.',
  },
  {
    id: 'math-4-patterns-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Patterns',
    question: 'Look at the pattern: ●○●○●○___. What comes next?',
    options: ['○', '●', 'Both', 'Neither'],
    correctIndex: 0,
    explanation: 'The pattern alternates between ● and ○ — after ● comes ○.',
  },
  {
    id: 'math-4-patterns-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Patterns',
    question: 'What is the missing number in this pattern? 40, 35, 30, ___, 20',
    options: ['25', '28', '22', '24'],
    correctIndex: 0,
    explanation: 'This pattern subtracts 5 each time: 30 − 5 = 25.',
  },

  // --- Data Handling and Probability: Pictographs & Bar Graphs ---
  {
    id: 'math-4-datahandling-1',
    subjectId: 'math',
    grade: 4,
    topic: 'Data Handling',
    question: 'In a pictograph, each 📘 represents 2 books. A row shows 📘📘📘. How many books does that represent?',
    options: ['6', '3', '2', '9'],
    correctIndex: 0,
    explanation: '3 pictures × 2 books each = 6 books.',
  },
  {
    id: 'math-4-datahandling-2',
    subjectId: 'math',
    grade: 4,
    topic: 'Data Handling',
    question: "A tally chart shows |||| for Monday's sales. How many items were sold on Monday?",
    options: ['4', '5', '3', '6'],
    correctIndex: 0,
    explanation: 'Each | is one tally mark, so |||| counts to 4.',
  },
  {
    id: 'math-4-datahandling-3',
    subjectId: 'math',
    grade: 4,
    topic: 'Data Handling',
    question: "In a bar graph, the bar for 'Mangoes' reaches 8 and the bar for 'Oranges' reaches 5. How many more mangoes than oranges were there?",
    options: ['3', '13', '5', '8'],
    correctIndex: 0,
    explanation: '8 − 5 = 3 more mangoes.',
  },
  {
    id: 'math-4-datahandling-4',
    subjectId: 'math',
    grade: 4,
    topic: 'Data Handling',
    question: 'A pictograph shows 🍊🍊🍊🍊 for oranges sold, where each 🍊 = 5 oranges. How many oranges were sold in total?',
    options: ['20', '9', '4', '25'],
    correctIndex: 0,
    explanation: '4 pictures × 5 oranges each = 20 oranges.',
  },
  {
    id: 'math-4-datahandling-5',
    subjectId: 'math',
    grade: 4,
    topic: 'Data Handling',
    question: 'Which type of chart uses bars of different heights to show amounts?',
    options: ['Bar graph', 'Pictograph', 'Tally chart', 'Pie chart'],
    correctIndex: 0,
    explanation: 'A bar graph uses bars — a taller bar means a bigger amount.',
  },
  {
    id: 'math-4-datahandling-6',
    subjectId: 'math',
    grade: 4,
    topic: 'Data Handling',
    question: 'In a class, 12 pupils like football, 8 like netball, and 5 like athletics. Which sport is the LEAST popular?',
    options: ['Athletics', 'Football', 'Netball', 'They are equal'],
    correctIndex: 0,
    explanation: '5 is the smallest number, so athletics is the least popular.',
  },

  // Grade 4 English, covering the CBC strands: Grammar (nouns/pronouns,
  // verbs/tenses, adjectives/punctuation), Vocabulary, and Reading.
  // --- Grammar: Nouns & Pronouns ---
  {
    id: 'english-4-nounspronouns-1',
    subjectId: 'english',
    grade: 4,
    topic: 'Nouns & Pronouns',
    question: "Which word in this sentence is a noun? 'The dog ran quickly.'",
    options: ['dog', 'ran', 'quickly', 'the'],
    correctIndex: 0,
    explanation: "A noun names a person, place, animal, or thing — 'dog' is the noun here.",
  },
  {
    id: 'english-4-nounspronouns-2',
    subjectId: 'english',
    grade: 4,
    topic: 'Nouns & Pronouns',
    question: "Which word is a pronoun? 'She went to the market.'",
    options: ['She', 'went', 'market', 'the'],
    correctIndex: 0,
    explanation: "A pronoun replaces a noun — 'She' stands in for a person's name.",
  },
  {
    id: 'english-4-nounspronouns-3',
    subjectId: 'english',
    grade: 4,
    topic: 'Nouns & Pronouns',
    question: 'Which of these is a proper noun that needs a capital letter?',
    options: ['kenya', 'country', 'city', 'river'],
    correctIndex: 0,
    explanation: "'Kenya' names a specific country, so it is a proper noun and should be written 'Kenya'.",
  },
  {
    id: 'english-4-nounspronouns-4',
    subjectId: 'english',
    grade: 4,
    topic: 'Nouns & Pronouns',
    question: 'Which sentence uses the correct pronoun?',
    options: ['He is my brother.', 'Him is my brother.', 'Her is my brother.', 'Them is my brother.'],
    correctIndex: 0,
    explanation: "'He' is the correct subject pronoun to use before a verb like 'is'.",
  },
  {
    id: 'english-4-nounspronouns-5',
    subjectId: 'english',
    grade: 4,
    topic: 'Nouns & Pronouns',
    question: "What is the plural of 'child'?",
    options: ['children', 'childs', 'childes', 'child'],
    correctIndex: 0,
    explanation: "'Child' has an irregular plural: 'children'.",
  },
  {
    id: 'english-4-nounspronouns-6',
    subjectId: 'english',
    grade: 4,
    topic: 'Nouns & Pronouns',
    question: 'Which word is a collective noun (names a group)?',
    options: ['flock', 'sheep', 'farmer', 'field'],
    correctIndex: 0,
    explanation: "A 'flock' names a group of animals, like sheep or birds.",
  },

  // --- Grammar: Verbs & Tenses ---
  {
    id: 'english-4-verbstenses-1',
    subjectId: 'english',
    grade: 4,
    topic: 'Verbs & Tenses',
    question: 'Which sentence is in the past tense?',
    options: [
      'She played football yesterday.',
      'She plays football today.',
      'She will play football tomorrow.',
      'She is playing football.',
    ],
    correctIndex: 0,
    explanation: "'Played' shows the action already happened — that is past tense.",
  },
  {
    id: 'english-4-verbstenses-2',
    subjectId: 'english',
    grade: 4,
    topic: 'Verbs & Tenses',
    question: "Choose the correct verb: 'They ___ to school every day.'",
    options: ['walk', 'walks', 'walked', 'walking'],
    correctIndex: 0,
    explanation: "'They' is plural, so the verb stays as 'walk' without an 's'.",
  },
  {
    id: 'english-4-verbstenses-3',
    subjectId: 'english',
    grade: 4,
    topic: 'Verbs & Tenses',
    question: "What is the past tense of 'go'?",
    options: ['went', 'goed', 'gos', 'going'],
    correctIndex: 0,
    explanation: "'Go' is an irregular verb — its past tense is 'went'.",
  },
  {
    id: 'english-4-verbstenses-4',
    subjectId: 'english',
    grade: 4,
    topic: 'Verbs & Tenses',
    question: "Choose the correct verb: 'He ___ his homework right now.'",
    options: ['is doing', 'do', 'did', 'does'],
    correctIndex: 0,
    explanation: "'Right now' tells us the action is happening at this moment, so we use 'is doing'.",
  },
  {
    id: 'english-4-verbstenses-5',
    subjectId: 'english',
    grade: 4,
    topic: 'Verbs & Tenses',
    question: 'Which sentence is in the future tense?',
    options: [
      'We will visit grandma next week.',
      'We visited grandma last week.',
      'We visit grandma every week.',
      'We are visiting grandma.',
    ],
    correctIndex: 0,
    explanation: "'Will visit' shows the action has not happened yet — that is future tense.",
  },
  {
    id: 'english-4-verbstenses-6',
    subjectId: 'english',
    grade: 4,
    topic: 'Verbs & Tenses',
    question: "Choose the correct verb: 'The baby ___ loudly.'",
    options: ['cries', 'cry', 'cried', 'crying'],
    correctIndex: 0,
    explanation: "'The baby' is singular, so the verb takes an 's': 'cries'.",
  },

  // --- Grammar: Adjectives & Punctuation ---
  {
    id: 'english-4-adjectivespunctuation-1',
    subjectId: 'english',
    grade: 4,
    topic: 'Adjectives & Punctuation',
    question: "Which word is an adjective in this sentence? 'The tall boy ran fast.'",
    options: ['tall', 'boy', 'ran', 'fast'],
    correctIndex: 0,
    explanation: "An adjective describes a noun — 'tall' describes the boy.",
  },
  {
    id: 'english-4-adjectivespunctuation-2',
    subjectId: 'english',
    grade: 4,
    topic: 'Adjectives & Punctuation',
    question: 'Which sentence ends with the correct punctuation?',
    options: ['What is your name?', 'What is your name.', 'What is your name!', 'What is your name,'],
    correctIndex: 0,
    explanation: 'A question ends with a question mark (?).',
  },
  {
    id: 'english-4-adjectivespunctuation-3',
    subjectId: 'english',
    grade: 4,
    topic: 'Adjectives & Punctuation',
    question: "Which word correctly completes the sentence? 'This is ___ apple.'",
    options: ['an', 'a', 'the a', 'some a'],
    correctIndex: 0,
    explanation: "We use 'an' before words that start with a vowel sound, like 'apple'.",
  },
  {
    id: 'english-4-adjectivespunctuation-4',
    subjectId: 'english',
    grade: 4,
    topic: 'Adjectives & Punctuation',
    question: 'Which sentence is written correctly?',
    options: ['Amani went to Nairobi.', 'amani went to nairobi.', 'Amani went to nairobi.', 'amani went to Nairobi.'],
    correctIndex: 0,
    explanation: 'Names of people and places (Amani, Nairobi) always start with a capital letter.',
  },
  {
    id: 'english-4-adjectivespunctuation-5',
    subjectId: 'english',
    grade: 4,
    topic: 'Adjectives & Punctuation',
    question: "Choose the correct comparative: 'This mango is ___ than that one.'",
    options: ['bigger', 'big', 'biggest', 'more big'],
    correctIndex: 0,
    explanation: "To compare two things, we usually add '-er': 'big' becomes 'bigger'.",
  },
  {
    id: 'english-4-adjectivespunctuation-6',
    subjectId: 'english',
    grade: 4,
    topic: 'Adjectives & Punctuation',
    question: 'Which punctuation mark shows strong feeling or excitement?',
    options: ['Exclamation mark (!)', 'Full stop (.)', 'Comma (,)', 'Question mark (?)'],
    correctIndex: 0,
    explanation: 'An exclamation mark shows strong feeling, like surprise or excitement.',
  },

  // --- Vocabulary: Synonyms & Antonyms ---
  {
    id: 'english-4-vocabulary-1',
    subjectId: 'english',
    grade: 4,
    topic: 'Synonyms & Antonyms',
    question: "Which word means the same as 'happy'?",
    options: ['glad', 'sad', 'angry', 'tired'],
    correctIndex: 0,
    explanation: "'Glad' is a synonym for 'happy' — they mean almost the same thing.",
  },
  {
    id: 'english-4-vocabulary-2',
    subjectId: 'english',
    grade: 4,
    topic: 'Synonyms & Antonyms',
    question: "Which word is the opposite of 'big'?",
    options: ['small', 'tall', 'wide', 'huge'],
    correctIndex: 0,
    explanation: "'Small' is the antonym (opposite) of 'big'.",
  },
  {
    id: 'english-4-vocabulary-3',
    subjectId: 'english',
    grade: 4,
    topic: 'Synonyms & Antonyms',
    question: "Which word means the same as 'quick'?",
    options: ['fast', 'slow', 'late', 'early'],
    correctIndex: 0,
    explanation: "'Fast' and 'quick' are synonyms.",
  },
  {
    id: 'english-4-vocabulary-4',
    subjectId: 'english',
    grade: 4,
    topic: 'Synonyms & Antonyms',
    question: "Which word is the opposite of 'begin'?",
    options: ['end', 'start', 'open', 'continue'],
    correctIndex: 0,
    explanation: "'End' is the antonym of 'begin'.",
  },
  {
    id: 'english-4-vocabulary-5',
    subjectId: 'english',
    grade: 4,
    topic: 'Synonyms & Antonyms',
    question: "Which word means the same as 'clean'?",
    options: ['neat', 'dirty', 'messy', 'wet'],
    correctIndex: 0,
    explanation: "'Neat' is a synonym for 'clean'.",
  },
  {
    id: 'english-4-vocabulary-6',
    subjectId: 'english',
    grade: 4,
    topic: 'Synonyms & Antonyms',
    question: "Which word is the opposite of 'strong'?",
    options: ['weak', 'tall', 'hard', 'brave'],
    correctIndex: 0,
    explanation: "'Weak' is the antonym of 'strong'.",
  },

  // --- Reading Comprehension ---
  {
    id: 'english-4-reading-1',
    subjectId: 'english',
    grade: 4,
    topic: 'Reading Comprehension',
    question:
      'Read: "Amina lives with her mother, father, and two brothers. Every evening, they eat dinner together and talk about their day." How many brothers does Amina have?',
    options: ['Two', 'One', 'Three', 'None'],
    correctIndex: 0,
    explanation: 'The passage says Amina lives with "two brothers."',
  },
  {
    id: 'english-4-reading-2',
    subjectId: 'english',
    grade: 4,
    topic: 'Reading Comprehension',
    question:
      'Read: "A balanced diet includes foods from different groups: proteins, carbohydrates, fruits, and vegetables. Eating a balanced diet keeps our bodies healthy." According to the passage, what does eating a balanced diet do?',
    options: ['Keeps our bodies healthy', 'Makes us tired', 'Makes us grow taller only', 'Has no effect'],
    correctIndex: 0,
    explanation: 'The passage states directly that a balanced diet "keeps our bodies healthy."',
  },
  {
    id: 'english-4-reading-3',
    subjectId: 'english',
    grade: 4,
    topic: 'Reading Comprehension',
    question:
      'Read: "Baraka fell off his bicycle and hurt his knee. His sister cleaned the wound and covered it with a bandage." What did Baraka\'s sister use to cover the wound?',
    options: ['A bandage', 'A blanket', 'A bucket', 'A book'],
    correctIndex: 0,
    explanation: 'The passage says she "covered it with a bandage."',
  },
  {
    id: 'english-4-reading-4',
    subjectId: 'english',
    grade: 4,
    topic: 'Reading Comprehension',
    question:
      'Read: "It is polite to say \'please\' when asking for something and \'thank you\' after receiving it. Good manners help us get along with others." What should you say after receiving something, according to the passage?',
    options: ['Thank you', 'Please', 'Sorry', 'Excuse me'],
    correctIndex: 0,
    explanation: 'The passage says to say "thank you" after receiving something.',
  },
  {
    id: 'english-4-reading-5',
    subjectId: 'english',
    grade: 4,
    topic: 'Reading Comprehension',
    question:
      'Read: "During the family celebration, everyone wore colourful clothes, sang songs, and shared a big meal together." Which of these did the family NOT do, based on the passage?',
    options: ['Watch a movie', 'Wear colourful clothes', 'Sing songs', 'Share a meal'],
    correctIndex: 0,
    explanation: 'The passage never mentions watching a movie — only clothes, songs, and a meal.',
  },
  {
    id: 'english-4-reading-6',
    subjectId: 'english',
    grade: 4,
    topic: 'Reading Comprehension',
    question:
      'Read: "Milk, eggs, and beans are good sources of protein. Protein helps our bodies grow strong." Which of these is NOT mentioned as a source of protein in the passage?',
    options: ['Rice', 'Milk', 'Eggs', 'Beans'],
    correctIndex: 0,
    explanation: 'The passage lists milk, eggs, and beans — rice is not mentioned.',
  },

  // Grade 4 Kiswahili, covering the CBC skills: Sarufi (ngeli za nomino,
  // vitenzi na nyakati, vivumishi na uakifishaji), Msamiati, na Ufahamu.
  // --- Sarufi: Ngeli za Nomino ---
  {
    id: 'kiswahili-4-ngeli-1',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ngeli za Nomino',
    question: "Nomino 'mtoto' iko katika ngeli gani?",
    options: ['M-WA', 'M-MI', 'KI-VI', 'N-N'],
    correctIndex: 0,
    explanation: "'Mtoto' ni nomino ya ngeli ya M-WA — wingi wake ni 'watoto'.",
  },
  {
    id: 'kiswahili-4-ngeli-2',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ngeli za Nomino',
    question: "Wingi wa 'kitabu' ni upi?",
    options: ['vitabu', 'vitabus', 'kitabus', 'matabu'],
    correctIndex: 0,
    explanation: "Nomino za ngeli ya KI-VI hubadilisha 'ki-' kuwa 'vi-' katika wingi: kitabu → vitabu.",
  },
  {
    id: 'kiswahili-4-ngeli-3',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ngeli za Nomino',
    question: "Nomino 'mti' iko katika ngeli gani?",
    options: ['M-MI', 'M-WA', 'KI-VI', 'U-U'],
    correctIndex: 0,
    explanation: "'Mti' ni nomino ya ngeli ya M-MI — wingi wake ni 'miti'.",
  },
  {
    id: 'kiswahili-4-ngeli-4',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ngeli za Nomino',
    question: "Wingi wa 'nyumba' ni upi?",
    options: ['nyumba', 'manyumba', 'vinyumba', 'nyumbaz'],
    correctIndex: 0,
    explanation: "Nomino za ngeli ya N-N kama 'nyumba' hazibadiliki katika wingi.",
  },
  {
    id: 'kiswahili-4-ngeli-5',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ngeli za Nomino',
    question: "Chagua wingi sahihi wa 'mtu'.",
    options: ['watu', 'mtus', 'watus', 'wamtu'],
    correctIndex: 0,
    explanation: "'Mtu' ni ngeli ya M-WA — wingi wake ni 'watu'.",
  },
  {
    id: 'kiswahili-4-ngeli-6',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ngeli za Nomino',
    question: "Nomino 'kiti' iko katika ngeli gani?",
    options: ['KI-VI', 'M-WA', 'M-MI', 'N-N'],
    correctIndex: 0,
    explanation: "'Kiti' ni ngeli ya KI-VI — wingi wake ni 'viti'.",
  },

  // --- Sarufi: Vitenzi na Nyakati ---
  {
    id: 'kiswahili-4-vitenzi-1',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vitenzi na Nyakati',
    question: 'Kiambishi -li- katika kitenzi kinaonyesha wakati gani?',
    options: ['Wakati uliopita', 'Wakati uliopo', 'Wakati ujao', 'Hakuna wakati'],
    correctIndex: 0,
    explanation: 'Kiambishi -li- kinaonyesha kitendo kilichotokea zamani (wakati uliopita).',
  },
  {
    id: 'kiswahili-4-vitenzi-2',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vitenzi na Nyakati',
    question: "Neno 'Alisoma' liko katika wakati gani?",
    options: ['Uliopita', 'Uliopo', 'Ujao', 'Timilifu'],
    correctIndex: 0,
    explanation: "Kiambishi -li- katika 'Alisoma' kinaonyesha wakati uliopita.",
  },
  {
    id: 'kiswahili-4-vitenzi-3',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vitenzi na Nyakati',
    question: 'Chagua kitenzi cha wakati ujao.',
    options: ['Atacheza', 'Anacheza', 'Alicheza', 'Amecheza'],
    correctIndex: 0,
    explanation: 'Kiambishi -ta- kinaonyesha wakati ujao — Atacheza.',
  },
  {
    id: 'kiswahili-4-vitenzi-4',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vitenzi na Nyakati',
    question: "'Tunacheza mpira' — kiambishi -na- kinaonyesha nini?",
    options: ['Kitendo kinachoendelea sasa', 'Kitendo kilichopita', 'Kitendo cha baadaye', 'Amri'],
    correctIndex: 0,
    explanation: 'Kiambishi -na- kinaonyesha kitendo kinachoendelea wakati huu.',
  },
  {
    id: 'kiswahili-4-vitenzi-5',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vitenzi na Nyakati',
    question: "Badilisha 'Ninakula' kuwa wakati uliopita.",
    options: ['Nilikula', 'Nitakula', 'Ninakula', 'Nimekula'],
    correctIndex: 0,
    explanation: 'Kiambishi -na- (uliopo) hubadilishwa kuwa -li- (uliopita): Ninakula → Nilikula.',
  },
  {
    id: 'kiswahili-4-vitenzi-6',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vitenzi na Nyakati',
    question: "Badilisha 'Anaandika' kuwa wakati ujao.",
    options: ['Ataandika', 'Aliandika', 'Anaandika', 'Ameandika'],
    correctIndex: 0,
    explanation: 'Kiambishi -na- (uliopo) hubadilishwa kuwa -ta- (ujao): Anaandika → Ataandika.',
  },

  // --- Sarufi: Vivumishi na Alama za Uakifishaji ---
  {
    id: 'kiswahili-4-vivumishi-1',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vivumishi na Uakifishaji',
    question: "Chagua kivumishi katika sentensi: 'Mtoto mrefu anaruka.'",
    options: ['mrefu', 'mtoto', 'anaruka', 'na'],
    correctIndex: 0,
    explanation: "'Mrefu' kinaeleza jinsi mtoto alivyo — ni kivumishi.",
  },
  {
    id: 'kiswahili-4-vivumishi-2',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vivumishi na Uakifishaji',
    question: 'Alama gani hutumika mwishoni mwa swali?',
    options: ['Alama ya kuuliza (?)', 'Kituo (.)', 'Mkato (,)', 'Alama ya mshangao (!)'],
    correctIndex: 0,
    explanation: 'Sentensi ya swali huishia na alama ya kuuliza (?).',
  },
  {
    id: 'kiswahili-4-vivumishi-3',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vivumishi na Uakifishaji',
    question: 'Sentensi ipi imeandikwa sawasawa?',
    options: ['Amina anaishi Nairobi.', 'amina anaishi nairobi.', 'Amina anaishi nairobi.', 'amina anaishi Nairobi.'],
    correctIndex: 0,
    explanation: 'Majina ya watu na mahali (Amina, Nairobi) huanza na herufi kubwa.',
  },
  {
    id: 'kiswahili-4-vivumishi-4',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vivumishi na Uakifishaji',
    question: "Chagua kivumishi kinachopatana na 'watoto'.",
    options: ['wazuri', 'mzuri', 'kizuri', 'nzuri'],
    correctIndex: 0,
    explanation: "Kivumishi hupatana na ngeli ya nomino — 'watoto' (ngeli ya WA) huchukua 'wazuri'.",
  },
  {
    id: 'kiswahili-4-vivumishi-5',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vivumishi na Uakifishaji',
    question: 'Alama gani huonyesha hisia kali au mshangao?',
    options: ['Alama ya mshangao (!)', 'Kituo (.)', 'Mkato (,)', 'Alama ya kuuliza (?)'],
    correctIndex: 0,
    explanation: 'Alama ya mshangao (!) huonyesha hisia kali, kama mshangao.',
  },
  {
    id: 'kiswahili-4-vivumishi-6',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Vivumishi na Uakifishaji',
    question: "Chagua kivumishi kinachopatana na 'mtoto'.",
    options: ['mzuri', 'wazuri', 'kizuri', 'nzuri'],
    correctIndex: 0,
    explanation: "'Mtoto' ni ngeli ya M (umoja) — huchukua kivumishi 'mzuri'.",
  },

  // --- Msamiati: Visawe na Vinyume ---
  {
    id: 'kiswahili-4-msamiati-1',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Visawe na Vinyume',
    question: "Kisawe cha 'furaha' ni kipi?",
    options: ['raha', 'huzuni', 'hasira', 'uchovu'],
    correctIndex: 0,
    explanation: "'Raha' na 'furaha' vina maana inayokaribiana.",
  },
  {
    id: 'kiswahili-4-msamiati-2',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Visawe na Vinyume',
    question: "Kinyume cha 'kubwa' ni kipi?",
    options: ['kidogo', 'refu', 'fupi', 'zito'],
    correctIndex: 0,
    explanation: "'Kidogo' ni kinyume cha 'kubwa'.",
  },
  {
    id: 'kiswahili-4-msamiati-3',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Visawe na Vinyume',
    question: "Kisawe cha 'haraka' ni kipi?",
    options: ['mbio', 'polepole', 'taratibu', 'chelewa'],
    correctIndex: 0,
    explanation: "'Mbio' na 'haraka' vyote vinahusiana na kwenda kwa kasi.",
  },
  {
    id: 'kiswahili-4-msamiati-4',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Visawe na Vinyume',
    question: "Kinyume cha 'safi' ni kipi?",
    options: ['chafu', 'nzuri', 'nyeupe', 'laini'],
    correctIndex: 0,
    explanation: "'Chafu' ni kinyume cha 'safi'.",
  },
  {
    id: 'kiswahili-4-msamiati-5',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Visawe na Vinyume',
    question: "Kisawe cha 'kusaidia' ni kipi?",
    options: ['kuauni', 'kuzuia', 'kupinga', 'kudhuru'],
    correctIndex: 0,
    explanation: "'Kuauni' na 'kusaidia' vyote vinamaanisha kumsaidia mtu.",
  },
  {
    id: 'kiswahili-4-msamiati-6',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Visawe na Vinyume',
    question: "Kinyume cha 'nzito' ni kipi?",
    options: ['nyepesi', 'kubwa', 'ndefu', 'fupi'],
    correctIndex: 0,
    explanation: "'Nyepesi' ni kinyume cha 'nzito'.",
  },

  // --- Ufahamu ---
  {
    id: 'kiswahili-4-ufahamu-1',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ufahamu',
    question:
      "Soma: \"Amina anaishi na mama yake, baba yake, na kaka wawili. Kila jioni, hula chakula pamoja na kuzungumza kuhusu siku yao.\" Amina ana kaka wangapi?",
    options: ['Wawili', 'Mmoja', 'Watatu', 'Hakuna'],
    correctIndex: 0,
    explanation: "Kifungu kinasema Amina anaishi na 'kaka wawili'.",
  },
  {
    id: 'kiswahili-4-ufahamu-2',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ufahamu',
    question:
      'Soma: "Chakula bora kina vyakula vya aina mbalimbali: protini, wanga, matunda, na mboga. Kula chakula bora huufanya mwili wetu kuwa na afya." Kulingana na kifungu, chakula bora hufanya nini?',
    options: ['Huufanya mwili kuwa na afya', 'Hufanya mwili kuwa mgonjwa', 'Hufanya tulale', 'Hakuna athari'],
    correctIndex: 0,
    explanation: 'Kifungu kinasema chakula bora "huufanya mwili wetu kuwa na afya."',
  },
  {
    id: 'kiswahili-4-ufahamu-3',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ufahamu',
    question:
      'Soma: "Baraka alianguka kutoka baiskeli yake na kuumiza goti lake. Dada yake alisafisha jeraha na kulifunga kwa bendeji." Dada yake Baraka alitumia nini kufunga jeraha?',
    options: ['Bendeji', 'Blanketi', 'Ndoo', 'Kitabu'],
    correctIndex: 0,
    explanation: 'Kifungu kinasema alilifunga jeraha "kwa bendeji."',
  },
  {
    id: 'kiswahili-4-ufahamu-4',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ufahamu',
    question:
      'Soma: "Ni adabu kusema \'tafadhali\' unapoomba kitu, na \'asante\' baada ya kupokea. Adabu njema hutusaidia kuishi vizuri na wengine." Kulingana na kifungu, tunapaswa kusema nini baada ya kupokea kitu?',
    options: ['Asante', 'Tafadhali', 'Samahani', 'Karibu'],
    correctIndex: 0,
    explanation: 'Kifungu kinasema tunasema "asante" baada ya kupokea kitu.',
  },
  {
    id: 'kiswahili-4-ufahamu-5',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ufahamu',
    question:
      'Soma: "Wakati wa sherehe ya familia, kila mtu alivaa nguo za rangi mbalimbali, akaimba nyimbo, na kula chakula pamoja." Familia haikufanya nini kulingana na kifungu?',
    options: ['Kutazama filamu', 'Kuvaa nguo za rangi', 'Kuimba nyimbo', 'Kula chakula pamoja'],
    correctIndex: 0,
    explanation: 'Kifungu hakitaji kutazama filamu — ni nguo, nyimbo, na chakula pekee.',
  },
  {
    id: 'kiswahili-4-ufahamu-6',
    subjectId: 'kiswahili',
    grade: 4,
    topic: 'Ufahamu',
    question:
      'Soma: "Maziwa, mayai, na maharagwe ni vyanzo vizuri vya protini. Protini husaidia miili yetu kukua na kuwa na nguvu." Kipi HAKITAJWI kama chanzo cha protini katika kifungu?',
    options: ['Mchele', 'Maziwa', 'Mayai', 'Maharagwe'],
    correctIndex: 0,
    explanation: 'Kifungu kinataja maziwa, mayai, na maharagwe — mchele haukutajwa.',
  },

  // Grade 4 Integrated Science, covering the KICD strands: Living Things
  // and Their Environment, Mixtures/Elements/Compounds, Force and Energy.
  // --- Living Things: Classification & Life Processes ---
  {
    id: 'science-4-livingthings-1',
    subjectId: 'science',
    grade: 4,
    topic: 'Classification & Life Processes',
    question: 'Which of these is a living thing?',
    options: ['A tree', 'A stone', 'A chair', 'A car'],
    correctIndex: 0,
    explanation: 'Living things grow, feed, and reproduce — a tree does all these; a stone does not.',
  },
  {
    id: 'science-4-livingthings-2',
    subjectId: 'science',
    grade: 4,
    topic: 'Classification & Life Processes',
    question: 'What do all living things need to survive?',
    options: ['Air, water, and food', 'Only water', 'Only sunlight', 'Nothing'],
    correctIndex: 0,
    explanation: 'All living things need air, water, and food to stay alive.',
  },
  {
    id: 'science-4-livingthings-3',
    subjectId: 'science',
    grade: 4,
    topic: 'Classification & Life Processes',
    question: 'Animals that eat only plants are called ___.',
    options: ['Herbivores', 'Carnivores', 'Omnivores', 'Decomposers'],
    correctIndex: 0,
    explanation: 'Herbivores are animals whose diet is only plants, like cows and rabbits.',
  },
  {
    id: 'science-4-livingthings-4',
    subjectId: 'science',
    grade: 4,
    topic: 'Classification & Life Processes',
    question: 'Animals that eat both plants and animals are called ___.',
    options: ['Omnivores', 'Herbivores', 'Carnivores', 'Producers'],
    correctIndex: 0,
    explanation: 'Omnivores eat both plants and animals, like humans and pigs.',
  },
  {
    id: 'science-4-livingthings-5',
    subjectId: 'science',
    grade: 4,
    topic: 'Classification & Life Processes',
    question: 'Which part of a plant absorbs water from the soil?',
    options: ['Roots', 'Leaves', 'Flowers', 'Stem'],
    correctIndex: 0,
    explanation: 'Roots grow into the soil and absorb water and nutrients.',
  },
  {
    id: 'science-4-livingthings-6',
    subjectId: 'science',
    grade: 4,
    topic: 'Classification & Life Processes',
    question: 'Which process do plants use to make their own food using sunlight?',
    options: ['Photosynthesis', 'Respiration', 'Digestion', 'Reproduction'],
    correctIndex: 0,
    explanation: 'Photosynthesis is how plants use sunlight, water, and air to make their own food.',
  },

  // --- Human Body & Health ---
  {
    id: 'science-4-humanbody-1',
    subjectId: 'science',
    grade: 4,
    topic: 'Human Body & Health',
    question: 'Which organ pumps blood around the body?',
    options: ['Heart', 'Lungs', 'Stomach', 'Brain'],
    correctIndex: 0,
    explanation: 'The heart pumps blood through the body, carrying oxygen and nutrients.',
  },
  {
    id: 'science-4-humanbody-2',
    subjectId: 'science',
    grade: 4,
    topic: 'Human Body & Health',
    question: 'Which organs help us breathe?',
    options: ['Lungs', 'Heart', 'Kidneys', 'Liver'],
    correctIndex: 0,
    explanation: 'The lungs take in oxygen and release carbon dioxide when we breathe.',
  },
  {
    id: 'science-4-humanbody-3',
    subjectId: 'science',
    grade: 4,
    topic: 'Human Body & Health',
    question: 'Which of these is a good habit for staying healthy?',
    options: ['Washing hands before eating', 'Eating only sweets', 'Sleeping very little', 'Skipping meals'],
    correctIndex: 0,
    explanation: 'Washing hands before eating removes germs and helps prevent illness.',
  },
  {
    id: 'science-4-humanbody-4',
    subjectId: 'science',
    grade: 4,
    topic: 'Human Body & Health',
    question: 'Which food group gives our body energy?',
    options: ['Carbohydrates', 'Vitamins only', 'Water only', 'None'],
    correctIndex: 0,
    explanation: 'Carbohydrates, found in foods like rice and ugali, give the body energy.',
  },
  {
    id: 'science-4-humanbody-5',
    subjectId: 'science',
    grade: 4,
    topic: 'Human Body & Health',
    question: 'What should you do immediately after playing outside and before eating?',
    options: ['Wash your hands', 'Go straight to eat', 'Sleep', 'Run more'],
    correctIndex: 0,
    explanation: 'Washing your hands removes dirt and germs picked up while playing.',
  },
  {
    id: 'science-4-humanbody-6',
    subjectId: 'science',
    grade: 4,
    topic: 'Human Body & Health',
    question: 'Which of these helps prevent the spread of germs?',
    options: ['Covering your mouth when you cough', 'Sharing cups with others', 'Not washing hands', 'Eating dirty food'],
    correctIndex: 0,
    explanation: 'Covering your mouth when coughing stops germs from spreading to others.',
  },

  // --- Materials & Mixtures ---
  {
    id: 'science-4-materials-1',
    subjectId: 'science',
    grade: 4,
    topic: 'Materials & Mixtures',
    question: 'Water, ice, and steam are the same substance in different states. Which state is water in its solid form?',
    options: ['Ice', 'Steam', 'Vapour', 'Liquid'],
    correctIndex: 0,
    explanation: 'Ice is water in its solid state, formed when water freezes.',
  },
  {
    id: 'science-4-materials-2',
    subjectId: 'science',
    grade: 4,
    topic: 'Materials & Mixtures',
    question: 'Which of these is an example of a mixture?',
    options: ['Sand and water', 'Pure water', 'Oxygen gas', 'Salt only'],
    correctIndex: 0,
    explanation: 'Sand and water are two different substances combined without chemically joining — a mixture.',
  },
  {
    id: 'science-4-materials-3',
    subjectId: 'science',
    grade: 4,
    topic: 'Materials & Mixtures',
    question: 'How can you separate sand from water?',
    options: ['Filtering', 'Melting', 'Freezing', 'Burning'],
    correctIndex: 0,
    explanation: 'Filtering lets water pass through while trapping the sand.',
  },
  {
    id: 'science-4-materials-4',
    subjectId: 'science',
    grade: 4,
    topic: 'Materials & Mixtures',
    question: 'What happens to water when it is heated to boiling point?',
    options: ['It turns into steam (gas)', 'It turns into ice', 'It disappears completely', 'It turns into sand'],
    correctIndex: 0,
    explanation: 'Heating water to boiling point turns it into steam, a gas.',
  },
  {
    id: 'science-4-materials-5',
    subjectId: 'science',
    grade: 4,
    topic: 'Materials & Mixtures',
    question: 'Which of these materials is magnetic (attracted to a magnet)?',
    options: ['Iron nail', 'Plastic ruler', 'Wooden stick', 'Paper'],
    correctIndex: 0,
    explanation: 'Iron is a magnetic metal, so an iron nail is attracted to a magnet.',
  },
  {
    id: 'science-4-materials-6',
    subjectId: 'science',
    grade: 4,
    topic: 'Materials & Mixtures',
    question: 'What is it called when water turns into vapour due to heat?',
    options: ['Evaporation', 'Condensation', 'Freezing', 'Melting'],
    correctIndex: 0,
    explanation: 'Evaporation is when a liquid like water turns into a gas due to heat.',
  },

  // --- Force & Energy ---
  {
    id: 'science-4-forceenergy-1',
    subjectId: 'science',
    grade: 4,
    topic: 'Force & Energy',
    question: 'A push or pull on an object is called a ___.',
    options: ['Force', 'Energy', 'Mass', 'Weight'],
    correctIndex: 0,
    explanation: 'A force is any push or pull that can move or change an object.',
  },
  {
    id: 'science-4-forceenergy-2',
    subjectId: 'science',
    grade: 4,
    topic: 'Force & Energy',
    question: 'Which of these is a source of light energy?',
    options: ['The sun', 'A stone', 'A book', 'Water'],
    correctIndex: 0,
    explanation: 'The sun gives off light energy that reaches the earth.',
  },
  {
    id: 'science-4-forceenergy-3',
    subjectId: 'science',
    grade: 4,
    topic: 'Force & Energy',
    question: 'A simple machine that uses a wheel and rope to help lift heavy loads is called a ___.',
    options: ['Pulley', 'Lever', 'Wedge', 'Screw'],
    correctIndex: 0,
    explanation: 'A pulley uses a wheel and rope to make lifting heavy objects easier.',
  },
  {
    id: 'science-4-forceenergy-4',
    subjectId: 'science',
    grade: 4,
    topic: 'Force & Energy',
    question: 'Which of these uses electrical energy?',
    options: ['A light bulb', 'A wooden chair', 'A stone', 'A leaf'],
    correctIndex: 0,
    explanation: 'A light bulb converts electrical energy into light.',
  },
  {
    id: 'science-4-forceenergy-5',
    subjectId: 'science',
    grade: 4,
    topic: 'Force & Energy',
    question: 'What force pulls objects down towards the earth?',
    options: ['Gravity', 'Friction', 'Magnetism', 'Wind'],
    correctIndex: 0,
    explanation: 'Gravity is the force that pulls objects towards the earth.',
  },
  {
    id: 'science-4-forceenergy-6',
    subjectId: 'science',
    grade: 4,
    topic: 'Force & Energy',
    question: 'Which of these is a renewable source of energy?',
    options: ['Sunlight', 'Coal', 'Petrol', 'Charcoal'],
    correctIndex: 0,
    explanation: 'Sunlight is renewable — it does not run out, unlike coal or petrol.',
  },

  // --- Environment & Conservation ---
  {
    id: 'science-4-environment-1',
    subjectId: 'science',
    grade: 4,
    topic: 'Environment & Conservation',
    question: 'Why is it important to plant trees?',
    options: [
      'They provide oxygen and prevent soil erosion',
      'They make the air dirty',
      'They use up all the water',
      'They have no benefit',
    ],
    correctIndex: 0,
    explanation: 'Trees release oxygen and their roots hold soil in place, preventing erosion.',
  },
  {
    id: 'science-4-environment-2',
    subjectId: 'science',
    grade: 4,
    topic: 'Environment & Conservation',
    question: 'Which of these actions helps conserve water?',
    options: ['Turning off the tap when not in use', 'Leaving the tap running', 'Wasting water', 'Using more water than needed'],
    correctIndex: 0,
    explanation: 'Turning off the tap when not needed saves water for later use.',
  },
  {
    id: 'science-4-environment-3',
    subjectId: 'science',
    grade: 4,
    topic: 'Environment & Conservation',
    question: 'What is pollution?',
    options: ['Adding harmful substances to the environment', 'Planting trees', 'Cleaning the environment', 'Recycling waste'],
    correctIndex: 0,
    explanation: 'Pollution is when harmful substances are added to air, water, or land.',
  },
  {
    id: 'science-4-environment-4',
    subjectId: 'science',
    grade: 4,
    topic: 'Environment & Conservation',
    question: 'Which of these is a way to reduce waste?',
    options: ['Reusing items instead of throwing them away', 'Burning all rubbish', 'Throwing litter everywhere', 'Buying more plastic'],
    correctIndex: 0,
    explanation: 'Reusing items means less new material is needed and less waste is created.',
  },
  {
    id: 'science-4-environment-5',
    subjectId: 'science',
    grade: 4,
    topic: 'Environment & Conservation',
    question: 'Which of these animals is most at risk if a forest is cut down?',
    options: ['Animals that live in the forest', 'Fish in the ocean', 'Animals in the desert', 'None are affected'],
    correctIndex: 0,
    explanation: 'Cutting down a forest destroys the habitat of the animals living there.',
  },
  {
    id: 'science-4-environment-6',
    subjectId: 'science',
    grade: 4,
    topic: 'Environment & Conservation',
    question: 'What can we do to protect wildlife?',
    options: ['Avoid destroying their habitats', 'Hunt them for fun', 'Cut down all trees', 'Ignore conservation rules'],
    correctIndex: 0,
    explanation: 'Protecting wildlife habitats helps animal populations survive.',
  },

  // Grade 4 Social Studies, covering the KICD strands: Natural & Built
  // Environment, People and Populations, Culture, Resources, Enterprise,
  // Citizenship.
  // --- Our Environment ---
  {
    id: 'social-4-environment-1',
    subjectId: 'social',
    grade: 4,
    topic: 'Our Environment',
    question: 'Which of these is a natural feature of the environment?',
    options: ['A mountain', 'A road', 'A school building', 'A bridge'],
    correctIndex: 0,
    explanation: 'A mountain is formed by nature, not built by people.',
  },
  {
    id: 'social-4-environment-2',
    subjectId: 'social',
    grade: 4,
    topic: 'Our Environment',
    question: 'Which of these is a built (man-made) feature?',
    options: ['A road', 'A river', 'A forest', 'A hill'],
    correctIndex: 0,
    explanation: 'A road is constructed by people — it is a built feature.',
  },
  {
    id: 'social-4-environment-3',
    subjectId: 'social',
    grade: 4,
    topic: 'Our Environment',
    question: 'What is the main source of fresh water for most communities?',
    options: ['Rivers and lakes', 'The ocean', 'The sky only', 'Underground oil'],
    correctIndex: 0,
    explanation: 'Rivers and lakes provide fresh water that communities use daily.',
  },
  {
    id: 'social-4-environment-4',
    subjectId: 'social',
    grade: 4,
    topic: 'Our Environment',
    question: 'Which activity can damage the natural environment?',
    options: ['Cutting down forests carelessly', 'Planting trees', 'Recycling', 'Conserving water'],
    correctIndex: 0,
    explanation: 'Careless deforestation destroys habitats and can cause soil erosion.',
  },
  {
    id: 'social-4-environment-5',
    subjectId: 'social',
    grade: 4,
    topic: 'Our Environment',
    question: 'What is a map used for?',
    options: ['Showing the location of places', 'Telling the time', 'Cooking food', 'Playing games'],
    correctIndex: 0,
    explanation: 'A map shows where places are located and how to get to them.',
  },
  {
    id: 'social-4-environment-6',
    subjectId: 'social',
    grade: 4,
    topic: 'Our Environment',
    question: 'Which of these shows directions on a map?',
    options: ['A compass', 'A ruler', 'A calendar', 'A clock'],
    correctIndex: 0,
    explanation: 'A compass shows North, South, East, and West on a map.',
  },

  // --- People & Population ---
  {
    id: 'social-4-population-1',
    subjectId: 'social',
    grade: 4,
    topic: 'People & Population',
    question: 'A place where many people live together is called a ___.',
    options: ['Settlement', 'Desert', 'Ocean', 'Forest'],
    correctIndex: 0,
    explanation: 'A settlement is a place where people live, such as a village or town.',
  },
  {
    id: 'social-4-population-2',
    subjectId: 'social',
    grade: 4,
    topic: 'People & Population',
    question: 'Which of these is an example of a rural area?',
    options: ['A farming village', 'A busy city', 'A shopping mall', 'An airport'],
    correctIndex: 0,
    explanation: 'Rural areas are typically farming communities with fewer people than cities.',
  },
  {
    id: 'social-4-population-3',
    subjectId: 'social',
    grade: 4,
    topic: 'People & Population',
    question: 'Which of these is an example of an urban area?',
    options: ['A big city', 'A small farming village', 'A forest', 'A desert'],
    correctIndex: 0,
    explanation: 'Urban areas are busy towns and cities with many people and buildings.',
  },
  {
    id: 'social-4-population-4',
    subjectId: 'social',
    grade: 4,
    topic: 'People & Population',
    question: 'Why do people migrate (move) from one place to another?',
    options: [
      'To look for better opportunities like jobs',
      'To avoid eating food',
      'To stop learning',
      'For no reason at all',
    ],
    correctIndex: 0,
    explanation: 'People often migrate to find better jobs, schools, or living conditions.',
  },
  {
    id: 'social-4-population-5',
    subjectId: 'social',
    grade: 4,
    topic: 'People & Population',
    question: 'What do we call counting the number of people living in an area?',
    options: ['A census', 'A map', 'A calendar', 'A survey of animals'],
    correctIndex: 0,
    explanation: 'A census is an official count of the people living in a place.',
  },
  {
    id: 'social-4-population-6',
    subjectId: 'social',
    grade: 4,
    topic: 'People & Population',
    question: 'Which of these is a basic need for all people?',
    options: ['Food, water, and shelter', 'Toys only', 'Money only', 'Cars only'],
    correctIndex: 0,
    explanation: 'Food, water, and shelter are basic needs every person requires to survive.',
  },

  // --- Culture & Heritage ---
  {
    id: 'social-4-culture-1',
    subjectId: 'social',
    grade: 4,
    topic: 'Culture & Heritage',
    question: 'What is culture?',
    options: [
      'The way of life of a group of people, including customs and traditions',
      'Only the food people eat',
      'Only the clothes people wear',
      'Only the language people speak',
    ],
    correctIndex: 0,
    explanation: 'Culture includes customs, traditions, language, food, and more — a whole way of life.',
  },
  {
    id: 'social-4-culture-2',
    subjectId: 'social',
    grade: 4,
    topic: 'Culture & Heritage',
    question: 'Which of these is part of Kenyan culture?',
    options: ['Traditional songs and dances', 'Only foreign movies', 'Only foreign food', 'None of these'],
    correctIndex: 0,
    explanation: 'Traditional songs and dances are an important part of Kenyan communities’ culture.',
  },
  {
    id: 'social-4-culture-3',
    subjectId: 'social',
    grade: 4,
    topic: 'Culture & Heritage',
    question: 'Why is it important to respect different cultures?',
    options: ['It helps people live together peacefully', 'It causes conflict', 'It is not important', 'It only benefits one group'],
    correctIndex: 0,
    explanation: 'Respecting different cultures helps communities live together in harmony.',
  },
  {
    id: 'social-4-culture-4',
    subjectId: 'social',
    grade: 4,
    topic: 'Culture & Heritage',
    question: "What do we call objects from the past that show a community's history?",
    options: ['Cultural heritage/artifacts', 'Modern technology', 'Foreign goods', 'Toys'],
    correctIndex: 0,
    explanation: 'Cultural heritage includes artifacts and traditions passed down through generations.',
  },
  {
    id: 'social-4-culture-5',
    subjectId: 'social',
    grade: 4,
    topic: 'Culture & Heritage',
    question: 'Which of these is an example of a cultural practice?',
    options: ['A traditional wedding ceremony', 'Watching television', 'Using a phone', 'Driving a car'],
    correctIndex: 0,
    explanation: 'A traditional wedding ceremony reflects the customs of a community.',
  },
  {
    id: 'social-4-culture-6',
    subjectId: 'social',
    grade: 4,
    topic: 'Culture & Heritage',
    question: 'Kenya has many different communities. What does this diversity mean?',
    options: ['Kenya has many different ethnic groups and cultures', 'Kenya has only one culture', 'Kenya has no culture', 'Kenya has no communities'],
    correctIndex: 0,
    explanation: 'Kenya is home to over 40 different ethnic communities, each with its own culture.',
  },

  // --- Resources & Enterprise ---
  {
    id: 'social-4-resources-1',
    subjectId: 'social',
    grade: 4,
    topic: 'Resources & Enterprise',
    question: 'What is a natural resource?',
    options: [
      'Something from nature that people use, like water or trees',
      'Something made in a factory',
      'Money in a bank',
      'A toy',
    ],
    correctIndex: 0,
    explanation: 'Natural resources come from nature and are used by people, like water, trees, and minerals.',
  },
  {
    id: 'social-4-resources-2',
    subjectId: 'social',
    grade: 4,
    topic: 'Resources & Enterprise',
    question: 'Which of these is a natural resource?',
    options: ['Forests', 'Cars', 'Phones', 'Buildings'],
    correctIndex: 0,
    explanation: 'Forests occur naturally and provide wood, oxygen, and habitats.',
  },
  {
    id: 'social-4-resources-3',
    subjectId: 'social',
    grade: 4,
    topic: 'Resources & Enterprise',
    question: 'What is enterprise?',
    options: ['Starting and running a business activity', 'Only playing games', 'Sleeping all day', 'Watching television'],
    correctIndex: 0,
    explanation: 'Enterprise means starting and managing a business to provide goods or services.',
  },
  {
    id: 'social-4-resources-4',
    subjectId: 'social',
    grade: 4,
    topic: 'Resources & Enterprise',
    question: 'Why do people start small businesses?',
    options: ['To earn money and provide goods or services', 'To waste time', 'To avoid working', 'For no reason'],
    correctIndex: 0,
    explanation: 'Small businesses earn income while providing useful goods or services to others.',
  },
  {
    id: 'social-4-resources-5',
    subjectId: 'social',
    grade: 4,
    topic: 'Resources & Enterprise',
    question: 'Which of these is an example of a human-made resource?',
    options: ['A factory', 'A river', 'A forest', 'Sunlight'],
    correctIndex: 0,
    explanation: 'A factory is built by people — it is a human-made (capital) resource.',
  },
  {
    id: 'social-4-resources-6',
    subjectId: 'social',
    grade: 4,
    topic: 'Resources & Enterprise',
    question: 'Why should we use natural resources wisely?',
    options: [
      'So they do not run out for future generations',
      'So we can waste them quickly',
      'Because they are unlimited',
      'Because they don’t matter',
    ],
    correctIndex: 0,
    explanation: 'Using resources wisely ensures they remain available for future generations.',
  },

  // --- Citizenship & Government ---
  {
    id: 'social-4-citizenship-1',
    subjectId: 'social',
    grade: 4,
    topic: 'Citizenship & Government',
    question: 'What is a citizen?',
    options: ['A member of a country who has rights and duties', 'A visitor from another country', 'A type of animal', 'A building'],
    correctIndex: 0,
    explanation: 'A citizen is a legally recognized member of a country, with rights and responsibilities.',
  },
  {
    id: 'social-4-citizenship-2',
    subjectId: 'social',
    grade: 4,
    topic: 'Citizenship & Government',
    question: 'Which of these is a duty of a good citizen?',
    options: ['Obeying the laws of the country', 'Breaking the law', 'Littering everywhere', "Ignoring others' rights"],
    correctIndex: 0,
    explanation: 'Obeying laws is a basic duty that helps keep society safe and fair.',
  },
  {
    id: 'social-4-citizenship-3',
    subjectId: 'social',
    grade: 4,
    topic: 'Citizenship & Government',
    question: 'What is the capital city of Kenya?',
    options: ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
    correctIndex: 0,
    explanation: 'Nairobi is the capital city of Kenya.',
  },
  {
    id: 'social-4-citizenship-4',
    subjectId: 'social',
    grade: 4,
    topic: 'Citizenship & Government',
    question: 'Who is the head of government in Kenya?',
    options: ['The President', 'The Governor', 'The Chief', 'The Teacher'],
    correctIndex: 0,
    explanation: 'The President is the head of the national government in Kenya.',
  },
  {
    id: 'social-4-citizenship-5',
    subjectId: 'social',
    grade: 4,
    topic: 'Citizenship & Government',
    question: 'Why do countries have laws?',
    options: ['To keep order and protect people’s rights', 'To confuse people', 'To stop all freedom', 'For no reason'],
    correctIndex: 0,
    explanation: 'Laws keep order in society and protect the rights of everyone.',
  },
  {
    id: 'social-4-citizenship-6',
    subjectId: 'social',
    grade: 4,
    topic: 'Citizenship & Government',
    question: 'Which of these is a right every child has?',
    options: ['The right to education', 'The right to skip all responsibilities', 'The right to ignore others', 'The right to break rules'],
    correctIndex: 0,
    explanation: 'Every child has the right to education, recognized both in Kenya and internationally.',
  },

  // Grade 4 Creative Arts, covering the KICD strands: Creating and
  // Execution, Performance and Display, and Appreciation. Focused on
  // music/art/craft — sports-adjacent sub-strands under this learning area
  // are left for a dedicated PE pass later.
  // --- Music: Rhythm & Instruments ---
  {
    id: 'creative-4-musicrhythm-1',
    subjectId: 'creative',
    grade: 4,
    topic: 'Rhythm & Instruments',
    question: 'Which of these is a percussion instrument (played by hitting or shaking)?',
    options: ['Drum', 'Recorder', 'Flute', 'Violin'],
    correctIndex: 0,
    explanation: 'A drum is a percussion instrument, played by striking it.',
  },
  {
    id: 'creative-4-musicrhythm-2',
    subjectId: 'creative',
    grade: 4,
    topic: 'Rhythm & Instruments',
    question: 'What is rhythm in music?',
    options: ['A pattern of beats over time', 'The colour of a song', 'The smell of an instrument', 'A type of dance only'],
    correctIndex: 0,
    explanation: 'Rhythm is the pattern of beats and timing in a piece of music.',
  },
  {
    id: 'creative-4-musicrhythm-3',
    subjectId: 'creative',
    grade: 4,
    topic: 'Rhythm & Instruments',
    question: 'Which instrument is played by blowing air through it?',
    options: ['Recorder', 'Drum', 'Shaker', 'Xylophone'],
    correctIndex: 0,
    explanation: 'A recorder is a wind instrument, played by blowing air into it.',
  },
  {
    id: 'creative-4-musicrhythm-4',
    subjectId: 'creative',
    grade: 4,
    topic: 'Rhythm & Instruments',
    question: 'Clapping your hands in a steady pattern while singing is an example of keeping ___.',
    options: ['Rhythm', 'Silence', 'Colour', 'Weight'],
    correctIndex: 0,
    explanation: 'Steady clapping while singing helps keep the rhythm of the song.',
  },
  {
    id: 'creative-4-musicrhythm-5',
    subjectId: 'creative',
    grade: 4,
    topic: 'Rhythm & Instruments',
    question: 'Which of these instruments is traditionally used in many Kenyan communities for percussion?',
    options: ['Drum (ngoma)', 'Piano', 'Violin', 'Trumpet'],
    correctIndex: 0,
    explanation: 'The ngoma (drum) is a traditional percussion instrument used across many Kenyan communities.',
  },
  {
    id: 'creative-4-musicrhythm-6',
    subjectId: 'creative',
    grade: 4,
    topic: 'Rhythm & Instruments',
    question: 'What do we call a short musical pattern of notes that is repeated?',
    options: ['Melody', 'Silence', 'Volume', 'Texture'],
    correctIndex: 0,
    explanation: 'A melody is a sequence of musical notes that forms the tune.',
  },

  // --- Music: Songs & Performance ---
  {
    id: 'creative-4-songs-1',
    subjectId: 'creative',
    grade: 4,
    topic: 'Songs & Performance',
    question: 'Singing together as a group is called ___.',
    options: ['A choir', 'A solo', 'A dance', 'A drawing'],
    correctIndex: 0,
    explanation: 'A choir is a group of people who sing together.',
  },
  {
    id: 'creative-4-songs-2',
    subjectId: 'creative',
    grade: 4,
    topic: 'Songs & Performance',
    question: 'What should performers do before singing on stage?',
    options: ['Practice and rehearse', 'Skip practicing', 'Ignore the song', 'Leave the stage'],
    correctIndex: 0,
    explanation: 'Practicing and rehearsing helps performers do their best on stage.',
  },
  {
    id: 'creative-4-songs-3',
    subjectId: 'creative',
    grade: 4,
    topic: 'Songs & Performance',
    question: 'Which of these describes singing a song alone?',
    options: ['A solo performance', 'A choir performance', 'A group dance', 'An orchestra'],
    correctIndex: 0,
    explanation: 'A solo is a performance by one singer alone.',
  },
  {
    id: 'creative-4-songs-4',
    subjectId: 'creative',
    grade: 4,
    topic: 'Songs & Performance',
    question: 'Why is it important to listen to the beat when singing with others?',
    options: ['To stay together and in time', 'To sing louder than everyone', 'To finish first', 'To ignore the group'],
    correctIndex: 0,
    explanation: 'Listening to the beat keeps everyone singing together in time.',
  },
  {
    id: 'creative-4-songs-5',
    subjectId: 'creative',
    grade: 4,
    topic: 'Songs & Performance',
    question: 'What do we call the words of a song?',
    options: ['Lyrics', 'Rhythm', 'Tempo', 'Instrument'],
    correctIndex: 0,
    explanation: 'Lyrics are the words that are sung in a song.',
  },
  {
    id: 'creative-4-songs-6',
    subjectId: 'creative',
    grade: 4,
    topic: 'Songs & Performance',
    question: 'Which of these is good performance etiquette?',
    options: ['Respecting the audience and other performers', 'Talking loudly during a performance', 'Ignoring the conductor', 'Leaving early'],
    correctIndex: 0,
    explanation: 'Respecting the audience and fellow performers makes for a good performance.',
  },

  // --- Art & Craft: Colours & Materials ---
  {
    id: 'creative-4-colours-1',
    subjectId: 'creative',
    grade: 4,
    topic: 'Colours & Materials',
    question: 'Which of these are primary colours (colours that cannot be made by mixing others)?',
    options: ['Red, blue, and yellow', 'Green, orange, and purple', 'Black and white only', 'Pink and brown'],
    correctIndex: 0,
    explanation: 'Red, blue, and yellow are the primary colours — all other colours are mixed from these.',
  },
  {
    id: 'creative-4-colours-2',
    subjectId: 'creative',
    grade: 4,
    topic: 'Colours & Materials',
    question: 'What colour do you get when you mix blue and yellow?',
    options: ['Green', 'Purple', 'Orange', 'Brown'],
    correctIndex: 0,
    explanation: 'Blue and yellow mixed together make green.',
  },
  {
    id: 'creative-4-colours-3',
    subjectId: 'creative',
    grade: 4,
    topic: 'Colours & Materials',
    question: 'What colour do you get when you mix red and blue?',
    options: ['Purple', 'Green', 'Orange', 'Yellow'],
    correctIndex: 0,
    explanation: 'Red and blue mixed together make purple.',
  },
  {
    id: 'creative-4-colours-4',
    subjectId: 'creative',
    grade: 4,
    topic: 'Colours & Materials',
    question: 'Which of these materials can be used for craft work?',
    options: ['Recycled paper and bottle tops', 'Only new expensive materials', 'Nothing can be reused', 'Only glass'],
    correctIndex: 0,
    explanation: 'Recycled materials like paper and bottle tops are great, low-cost craft materials.',
  },
  {
    id: 'creative-4-colours-5',
    subjectId: 'creative',
    grade: 4,
    topic: 'Colours & Materials',
    question: 'What tool is commonly used to apply paint?',
    options: ['A paintbrush', 'A hammer', 'A ruler', 'A spoon'],
    correctIndex: 0,
    explanation: 'A paintbrush is the standard tool for applying paint.',
  },
  {
    id: 'creative-4-colours-6',
    subjectId: 'creative',
    grade: 4,
    topic: 'Colours & Materials',
    question: 'What colour do you get when you mix red and yellow?',
    options: ['Orange', 'Green', 'Purple', 'Black'],
    correctIndex: 0,
    explanation: 'Red and yellow mixed together make orange.',
  },

  // --- Art & Craft: Drawing & Design ---
  {
    id: 'creative-4-drawing-1',
    subjectId: 'creative',
    grade: 4,
    topic: 'Drawing & Design',
    question: 'Which of these is a basic shape used in drawing?',
    options: ['Circle', 'Rainbow', 'A cloud shape only', 'A star only'],
    correctIndex: 0,
    explanation: 'A circle is one of the basic shapes used to build up a drawing.',
  },
  {
    id: 'creative-4-drawing-2',
    subjectId: 'creative',
    grade: 4,
    topic: 'Drawing & Design',
    question: 'What is a pattern in art?',
    options: ['A design that repeats', 'A single colour', 'A blank page', 'A broken pencil'],
    correctIndex: 0,
    explanation: 'A pattern is a design or shape that repeats regularly.',
  },
  {
    id: 'creative-4-drawing-3',
    subjectId: 'creative',
    grade: 4,
    topic: 'Drawing & Design',
    question: 'Which tool would you use to draw a straight line?',
    options: ['A ruler', 'A paintbrush', 'A sponge', 'Your finger'],
    correctIndex: 0,
    explanation: 'A ruler guides your pencil to draw a straight, even line.',
  },
  {
    id: 'creative-4-drawing-4',
    subjectId: 'creative',
    grade: 4,
    topic: 'Drawing & Design',
    question: 'What do we call the part of a drawing that is behind the main subject?',
    options: ['Background', 'Foreground', 'Border', 'Frame'],
    correctIndex: 0,
    explanation: 'The background is the part of the drawing behind the main subject.',
  },
  {
    id: 'creative-4-drawing-5',
    subjectId: 'creative',
    grade: 4,
    topic: 'Drawing & Design',
    question: 'Which of these describes a 3-dimensional shape?',
    options: ['A cube', 'A circle', 'A square', 'A triangle'],
    correctIndex: 0,
    explanation: 'A cube has length, width, and height — unlike flat shapes like circles and squares.',
  },
  {
    id: 'creative-4-drawing-6',
    subjectId: 'creative',
    grade: 4,
    topic: 'Drawing & Design',
    question: 'Why do artists sketch before making a final drawing?',
    options: ['To plan out their ideas first', 'To waste paper', 'To avoid drawing well', 'It is not useful'],
    correctIndex: 0,
    explanation: 'Sketching first lets an artist plan and try out ideas before the final piece.',
  },

  // --- Appreciation: Critiquing Art ---
  {
    id: 'creative-4-appreciation-1',
    subjectId: 'creative',
    grade: 4,
    topic: 'Appreciation',
    question: "What does it mean to 'critique' an artwork?",
    options: ['To give thoughtful feedback about it', 'To destroy it', 'To ignore it completely', 'To copy it exactly'],
    correctIndex: 0,
    explanation: 'To critique means to thoughtfully discuss and evaluate a piece of art.',
  },
  {
    id: 'creative-4-appreciation-2',
    subjectId: 'creative',
    grade: 4,
    topic: 'Appreciation',
    question: 'When looking at an artwork, what can you comment on?',
    options: ['The colours, shapes, and how it makes you feel', 'Only the price', 'Only who made it', 'Nothing at all'],
    correctIndex: 0,
    explanation: 'Art can be discussed through its colours, shapes, and the feelings it creates.',
  },
  {
    id: 'creative-4-appreciation-3',
    subjectId: 'creative',
    grade: 4,
    topic: 'Appreciation',
    question: "Why is it useful to appreciate other people's artwork?",
    options: ['It helps us learn new ideas and respect creativity', 'It is a waste of time', 'It only helps the artist', 'It has no benefit'],
    correctIndex: 0,
    explanation: 'Appreciating others’ art teaches us new ideas and builds respect for creativity.',
  },
  {
    id: 'creative-4-appreciation-4',
    subjectId: 'creative',
    grade: 4,
    topic: 'Appreciation',
    question: 'When giving feedback on someone’s art, it is best to be ___.',
    options: ['Kind and helpful', 'Rude', 'Silent', 'Dismissive'],
    correctIndex: 0,
    explanation: 'Kind, helpful feedback encourages people to keep creating.',
  },
  {
    id: 'creative-4-appreciation-5',
    subjectId: 'creative',
    grade: 4,
    topic: 'Appreciation',
    question: 'What can you learn by appreciating traditional Kenyan art and craft?',
    options: ['About the culture and history behind it', 'Nothing useful', 'Only about modern art', 'About foreign countries only'],
    correctIndex: 0,
    explanation: 'Traditional art and craft often reflect a community’s culture and history.',
  },
  {
    id: 'creative-4-appreciation-6',
    subjectId: 'creative',
    grade: 4,
    topic: 'Appreciation',
    question: 'Which of these is a good question to ask when appreciating art?',
    options: ['What is this artwork trying to show or express?', 'How much did it cost?', 'Who is the richest artist?', 'Is this the newest artwork?'],
    correctIndex: 0,
    explanation: 'Thinking about what an artwork expresses is at the heart of appreciating it.',
  },

  // Grade 4 Religious Education, covering common CRE strands for this
  // level: the Bible, Creation, Christian Values, Prayer & Worship, and
  // Family & Community. CRE specifically (the most common option in CBC
  // schools); IRE/HRE decks would need their own content if needed later.
  // --- The Bible ---
  {
    id: 're-4-bible-1',
    subjectId: 're',
    grade: 4,
    topic: 'The Bible',
    question: 'The Bible is divided into two main parts. What are they called?',
    options: [
      'The Old Testament and the New Testament',
      'The First Book and the Second Book',
      'The Holy Book and the Prayer Book',
      'The Genesis and the Exodus',
    ],
    correctIndex: 0,
    explanation: 'The Bible has two main parts: the Old Testament and the New Testament.',
  },
  {
    id: 're-4-bible-2',
    subjectId: 're',
    grade: 4,
    topic: 'The Bible',
    question: 'Which part of the Bible tells us about the birth and life of Jesus?',
    options: ['The New Testament', 'The Old Testament', 'Neither part', 'Both equally'],
    correctIndex: 0,
    explanation: 'The New Testament tells the story of Jesus’s life and teachings.',
  },
  {
    id: 're-4-bible-3',
    subjectId: 're',
    grade: 4,
    topic: 'The Bible',
    question: 'How should we treat the Bible?',
    options: ['With care and respect', 'Carelessly', 'By throwing it around', 'It does not matter'],
    correctIndex: 0,
    explanation: 'Christians treat the Bible with care and respect as a holy book.',
  },
  {
    id: 're-4-bible-4',
    subjectId: 're',
    grade: 4,
    topic: 'The Bible',
    question: 'The Old Testament contains stories about creation and which people?',
    options: ['The Israelites and the Prophets', 'Only modern people', 'Only animals', 'Only kings of England'],
    correctIndex: 0,
    explanation: 'The Old Testament tells the stories of the Israelites and the Prophets.',
  },
  {
    id: 're-4-bible-5',
    subjectId: 're',
    grade: 4,
    topic: 'The Bible',
    question: 'Christians believe the Bible is important because ___.',
    options: ['It is how God speaks to His people', 'It is just an ordinary storybook', 'It has no meaning', 'It should be ignored'],
    correctIndex: 0,
    explanation: 'Christians believe the Bible is God’s word, speaking to His people.',
  },
  {
    id: 're-4-bible-6',
    subjectId: 're',
    grade: 4,
    topic: 'The Bible',
    question: 'What do we call the very first book of the Bible?',
    options: ['Genesis', 'Exodus', 'Matthew', 'Revelation'],
    correctIndex: 0,
    explanation: 'Genesis is the first book of the Bible and tells the story of creation.',
  },

  // --- Creation ---
  {
    id: 're-4-creation-1',
    subjectId: 're',
    grade: 4,
    topic: 'Creation',
    question: 'According to the Bible, who created the world?',
    options: ['God', 'Humans', 'Animals', 'No one'],
    correctIndex: 0,
    explanation: 'The book of Genesis tells how God created the world.',
  },
  {
    id: 're-4-creation-2',
    subjectId: 're',
    grade: 4,
    topic: 'Creation',
    question: 'According to the creation story, what makes each person special?',
    options: ['Each person is uniquely created', 'Everyone is exactly the same', 'Only some people are special', 'People are not important'],
    correctIndex: 0,
    explanation: 'The creation story teaches that every person is uniquely and specially made.',
  },
  {
    id: 're-4-creation-3',
    subjectId: 're',
    grade: 4,
    topic: 'Creation',
    question: "Who were the first man and woman according to the Bible's creation story?",
    options: ['Adam and Eve', 'Moses and Miriam', 'David and Goliath', 'Noah and his wife'],
    correctIndex: 0,
    explanation: 'Adam and Eve are named as the first man and woman in Genesis.',
  },
  {
    id: 're-4-creation-4',
    subjectId: 're',
    grade: 4,
    topic: 'Creation',
    question: 'How should we treat the things God created, like animals and plants?',
    options: ['With care and respect', 'By destroying them', 'It does not matter', 'By wasting them'],
    correctIndex: 0,
    explanation: 'Caring for creation is seen as an important responsibility.',
  },
  {
    id: 're-4-creation-5',
    subjectId: 're',
    grade: 4,
    topic: 'Creation',
    question: 'What can we learn from the creation story about the world around us?',
    options: ['It should be cared for and appreciated', 'It has no value', 'It belongs to no one', 'It should be ignored'],
    correctIndex: 0,
    explanation: 'The creation story teaches us to value and care for the world.',
  },
  {
    id: 're-4-creation-6',
    subjectId: 're',
    grade: 4,
    topic: 'Creation',
    question: 'Being thankful for creation means we should ___.',
    options: ['Take care of the environment', 'Waste natural resources', 'Ignore nature', 'Destroy plants and animals'],
    correctIndex: 0,
    explanation: 'Gratitude for creation is shown through caring for the environment.',
  },

  // --- Christian Values ---
  {
    id: 're-4-values-1',
    subjectId: 're',
    grade: 4,
    topic: 'Christian Values',
    question: 'What does obedience mean?',
    options: [
      'Listening and doing what you are asked by parents and teachers',
      'Ignoring instructions',
      'Doing whatever you want',
      'Arguing with everyone',
    ],
    correctIndex: 0,
    explanation: 'Obedience means listening to and following the guidance of parents and teachers.',
  },
  {
    id: 're-4-values-2',
    subjectId: 're',
    grade: 4,
    topic: 'Christian Values',
    question: 'Why is honesty an important value?',
    options: ['It helps build trust with others', 'It causes problems', 'It is not important', 'It only matters sometimes'],
    correctIndex: 0,
    explanation: 'Honesty builds trust between people.',
  },
  {
    id: 're-4-values-3',
    subjectId: 're',
    grade: 4,
    topic: 'Christian Values',
    question: 'What does it mean to show love to others?',
    options: ['Being kind and caring towards them', 'Ignoring their needs', 'Being unkind', 'Avoiding them'],
    correctIndex: 0,
    explanation: 'Showing love means being kind and caring towards others.',
  },
  {
    id: 're-4-values-4',
    subjectId: 're',
    grade: 4,
    topic: 'Christian Values',
    question: 'Which of these is an example of a good Christian value?',
    options: ['Helping someone in need', 'Bullying others', 'Lying to your parents', 'Being selfish'],
    correctIndex: 0,
    explanation: 'Helping others in need reflects the Christian value of love and compassion.',
  },
  {
    id: 're-4-values-5',
    subjectId: 're',
    grade: 4,
    topic: 'Christian Values',
    question: 'Why should we forgive others when they make mistakes?',
    options: ['It helps us live peacefully together', 'It shows weakness', 'It is unnecessary', 'It only benefits the other person'],
    correctIndex: 0,
    explanation: 'Forgiveness helps people live together in peace.',
  },
  {
    id: 're-4-values-6',
    subjectId: 're',
    grade: 4,
    topic: 'Christian Values',
    question: 'Being obedient at school helps ___.',
    options: ['Everyone learn and stay safe', 'Only the teacher', 'No one at all', 'Cause more problems'],
    correctIndex: 0,
    explanation: 'Obedience at school helps create a safe environment where everyone can learn.',
  },

  // --- Prayer & Worship ---
  {
    id: 're-4-prayer-1',
    subjectId: 're',
    grade: 4,
    topic: 'Prayer & Worship',
    question: 'What is prayer?',
    options: ['Talking to God', 'Reading any book', 'Watching television', 'Playing games'],
    correctIndex: 0,
    explanation: 'Prayer is how Christians communicate with God.',
  },
  {
    id: 're-4-prayer-2',
    subjectId: 're',
    grade: 4,
    topic: 'Prayer & Worship',
    question: 'Why do Christians pray?',
    options: ['To communicate with God and give thanks', 'To pass time only', 'Because it is required by law', 'For no reason'],
    correctIndex: 0,
    explanation: 'Christians pray to communicate with God and express gratitude.',
  },
  {
    id: 're-4-prayer-3',
    subjectId: 're',
    grade: 4,
    topic: 'Prayer & Worship',
    question: 'Where do Christians usually go to worship together?',
    options: ['Church', 'Market', 'Stadium', 'Cinema'],
    correctIndex: 0,
    explanation: 'Christians gather at church to worship together.',
  },
  {
    id: 're-4-prayer-4',
    subjectId: 're',
    grade: 4,
    topic: 'Prayer & Worship',
    question: 'Which of these is a good time to pray?',
    options: ['Anytime, including morning and before meals', 'Only on Sundays', 'Never', 'Only when in trouble'],
    correctIndex: 0,
    explanation: 'Christians are encouraged to pray at any time, not just on special occasions.',
  },
  {
    id: 're-4-prayer-5',
    subjectId: 're',
    grade: 4,
    topic: 'Prayer & Worship',
    question: 'What can we include when we pray?',
    options: ['Thanking God and asking for help', 'Only complaining', 'Only asking for toys', 'Nothing meaningful'],
    correctIndex: 0,
    explanation: 'Prayers often include thanksgiving and requests for guidance or help.',
  },
  {
    id: 're-4-prayer-6',
    subjectId: 're',
    grade: 4,
    topic: 'Prayer & Worship',
    question: 'Singing songs of praise during worship is called ___.',
    options: ['Hymns', 'Silence', 'Arguments', 'Homework'],
    correctIndex: 0,
    explanation: 'Hymns are songs of praise sung during Christian worship.',
  },

  // --- Family & Community ---
  {
    id: 're-4-family-1',
    subjectId: 're',
    grade: 4,
    topic: 'Family & Community',
    question: 'What is the smallest unit of a community?',
    options: ['The family', 'The school', 'The church', 'The government'],
    correctIndex: 0,
    explanation: 'The family is considered the smallest and most basic unit of a community.',
  },
  {
    id: 're-4-family-2',
    subjectId: 're',
    grade: 4,
    topic: 'Family & Community',
    question: 'Why is it important to respect our parents and elders?',
    options: ['They guide and care for us', 'They have no role in our lives', 'It is not necessary', 'Only sometimes'],
    correctIndex: 0,
    explanation: 'Parents and elders guide and care for children, which is why they deserve respect.',
  },
  {
    id: 're-4-family-3',
    subjectId: 're',
    grade: 4,
    topic: 'Family & Community',
    question: 'How can children help at home?',
    options: ['By doing simple chores and being responsible', 'By refusing to help', 'By making more work for others', 'By ignoring family members'],
    correctIndex: 0,
    explanation: 'Children can help at home by doing simple chores and being responsible.',
  },
  {
    id: 're-4-family-4',
    subjectId: 're',
    grade: 4,
    topic: 'Family & Community',
    question: 'What makes a strong community?',
    options: ['People supporting and caring for one another', 'People ignoring each other', 'People fighting often', 'People living alone'],
    correctIndex: 0,
    explanation: 'A strong community is built on people supporting and caring for one another.',
  },
  {
    id: 're-4-family-5',
    subjectId: 're',
    grade: 4,
    topic: 'Family & Community',
    question: "Why should we appreciate the different roles each family member plays?",
    options: [
      "Everyone contributes to the family's wellbeing",
      "Only one person's role matters",
      'Roles do not matter',
      'Family members should not help each other',
    ],
    correctIndex: 0,
    explanation: 'Every family member’s role contributes to the wellbeing of the whole family.',
  },
  {
    id: 're-4-family-6',
    subjectId: 're',
    grade: 4,
    topic: 'Family & Community',
    question: 'Which of these shows good behaviour towards neighbours?',
    options: ['Being kind and helpful', 'Being rude', 'Ignoring them completely', 'Causing trouble'],
    correctIndex: 0,
    explanation: 'Being kind and helpful towards neighbours builds a healthy community.',
  },
];
